import {
  Ticket,
  Customer,
  KnowledgeBaseArticle,
  DashboardStats,
} from "@/types";

// Mock data - replace with real Supabase queries in production
export const mockUser = {
  id: "1",
  company_id: "1",
  name: "Admin",
  email: "admin@empresa.com",
  role: "admin" as const,
  is_agent: true,
};

export const mockTickets: Ticket[] = [
  {
    id: "TK-001",
    company_id: "1",
    customer_id: "1",
    created_by: "1",
    assigned_to: "1",
    subject: "Não consigo acessar o sistema",
    description: "Estou tentando fazer login mas recebo erro de credenciais inválidas.",
    status: "open",
    priority: "high",
    category: "technical",
    ai_suggested_response: "Olá! Verifique se seu e-mail e senha estão corretos. Tente redefinir a senha.",
    ai_classification: "Suporte técnico - Acesso",
    ai_priority_suggestion: "high",
    created_at: new Date(Date.now() - 3600000).toISOString(),
    updated_at: new Date(Date.now() - 3600000).toISOString(),
    resolved_at: null,
    closed_at: null,
  },
  {
    id: "TK-002",
    company_id: "1",
    customer_id: "2",
    created_by: "2",
    assigned_to: "1",
    subject: "Dúvida sobre cobrança",
    description: "Fui cobrado duas vezes este mês. Preciso de estorno.",
    status: "in_progress",
    priority: "urgent",
    category: "billing",
    ai_suggested_response: "Lamentamos o ocorrido. Vamos analisar sua fatura e providenciar o estorno.",
    ai_classification: "Financeiro - Cobrança duplicada",
    ai_priority_suggestion: "urgent",
    created_at: new Date(Date.now() - 7200000).toISOString(),
    updated_at: new Date(Date.now() - 1800000).toISOString(),
    resolved_at: null,
    closed_at: null,
  },
  {
    id: "TK-003",
    company_id: "1",
    customer_id: "3",
    created_by: "3",
    assigned_to: null,
    subject: "Solicitação de nova funcionalidade",
    description: "Gostaria de sugerir a inclusão de exportação em PDF nos relatórios.",
    status: "open",
    priority: "low",
    category: "feedback",
    ai_suggested_response: null,
    ai_classification: null,
    ai_priority_suggestion: null,
    created_at: new Date(Date.now() - 86400000).toISOString(),
    updated_at: new Date(Date.now() - 86400000).toISOString(),
    resolved_at: null,
    closed_at: null,
  },
  {
    id: "TK-004",
    company_id: "1",
    customer_id: "1",
    created_by: "1",
    assigned_to: "2",
    subject: "Problema com envio de e-mails",
    description: "Os e-mails transacionais não estão sendo enviados aos clientes.",
    status: "resolved",
    priority: "high",
    category: "technical",
    ai_suggested_response: "O problema foi identificado na configuração SMTP. Já foi corrigido.",
    ai_classification: "Técnico - E-mail",
    ai_priority_suggestion: "high",
    created_at: new Date(Date.now() - 172800000).toISOString(),
    updated_at: new Date(Date.now() - 3600000).toISOString(),
    resolved_at: new Date(Date.now() - 3600000).toISOString(),
    closed_at: null,
  },
  {
    id: "TK-005",
    company_id: "1",
    customer_id: "4",
    created_by: "4",
    assigned_to: "1",
    subject: "Integração com WhatsApp",
    description: "Como configurar a integração com WhatsApp Business?",
    status: "closed",
    priority: "medium",
    category: "sales",
    ai_suggested_response: null,
    ai_classification: null,
    ai_priority_suggestion: null,
    created_at: new Date(Date.now() - 259200000).toISOString(),
    updated_at: new Date(Date.now() - 86400000).toISOString(),
    resolved_at: new Date(Date.now() - 172800000).toISOString(),
    closed_at: new Date(Date.now() - 86400000).toISOString(),
  },
];

export const mockCustomers: Customer[] = [
  { id: "1", company_id: "1", name: "João Silva", email: "joao@email.com", phone: "(11) 99999-0001", company_name: "Empresa A", notes: "Cliente desde 2024", created_at: "2024-01-15T10:00:00Z", updated_at: "2024-01-15T10:00:00Z" },
  { id: "2", company_id: "1", name: "Maria Santos", email: "maria@email.com", phone: "(11) 99999-0002", company_name: "Empresa B", notes: null, created_at: "2024-02-20T10:00:00Z", updated_at: "2024-02-20T10:00:00Z" },
  { id: "3", company_id: "1", name: "Carlos Oliveira", email: "carlos@email.com", phone: null, company_name: "Empresa C", notes: "Prefere contato via e-mail", created_at: "2024-03-10T10:00:00Z", updated_at: "2024-03-10T10:00:00Z" },
  { id: "4", company_id: "1", name: "Ana Pereira", email: "ana@email.com", phone: "(21) 99999-0004", company_name: "Empresa D", notes: null, created_at: "2024-04-05T10:00:00Z", updated_at: "2024-04-05T10:00:00Z" },
];

export const mockArticles: KnowledgeBaseArticle[] = [
  { id: "1", company_id: "1", title: "Como redefinir sua senha", content: "Acesse a página de login e clique em 'Esqueci minha senha'. Você receberá um e-mail com instruções.", category: "Acesso", is_published: true, views: 245, created_by: "1", created_at: "2024-01-10T10:00:00Z", updated_at: "2024-01-10T10:00:00Z" },
  { id: "2", company_id: "1", title: "Configurando seu perfil", content: "Vá em Configurações > Perfil para editar suas informações pessoais e foto.", category: "Configuração", is_published: true, views: 128, created_by: "1", created_at: "2024-02-15T10:00:00Z", updated_at: "2024-02-15T10:00:00Z" },
  { id: "3", company_id: "1", title: "Formas de pagamento aceitas", content: "Aceitamos cartão de crédito, boleto bancário e PIX. Para planos anuais, há desconto de 20%.", category: "Financeiro", is_published: true, views: 89, created_by: "1", created_at: "2024-03-20T10:00:00Z", updated_at: "2024-03-20T10:00:00Z" },
];

export const mockStats: DashboardStats = {
  totalTickets: 1247,
  openTickets: 23,
  resolvedTickets: 1180,
  inProgressTickets: 44,
  newTicketsToday: 12,
  averageResponseTime: 18,
  ticketsByStatus: [
    { status: "Aberto", count: 23 },
    { status: "Em andamento", count: 44 },
    { status: "Resolvido", count: 1180 },
    { status: "Fechado", count: 356 },
  ],
  ticketsByPriority: [
    { priority: "Baixa", count: 420 },
    { priority: "Média", count: 580 },
    { priority: "Alta", count: 210 },
    { priority: "Urgente", count: 37 },
  ],
  ticketsByDay: [
    { date: "2024-04-01", count: 8 },
    { date: "2024-04-02", count: 15 },
    { date: "2024-04-03", count: 12 },
    { date: "2024-04-04", count: 20 },
    { date: "2024-04-05", count: 18 },
    { date: "2024-04-06", count: 5 },
    { date: "2024-04-07", count: 12 },
  ],
  agentsPerformance: [
    { name: "Ana Silva", resolved: 156, open: 12 },
    { name: "Bruno Costa", resolved: 142, open: 18 },
    { name: "Carla Dias", resolved: 98, open: 8 },
  ],
};

export const mockAgents = [
  { id: "1", name: "Ana Silva", email: "ana@empresa.com", role: "agent", status: "online", tickets: 12 },
  { id: "2", name: "Bruno Costa", email: "bruno@empresa.com", role: "agent", status: "offline", tickets: 8 },
  { id: "3", name: "Carla Dias", email: "carla@empresa.com", role: "agent", status: "online", tickets: 5 },
];
